name: Deploy to Github Pages

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo npm i -g pnpm
          pnpm install --no-frozen-lockfile
      - name: Build
        run: |
          pnpm build
          pnpm export
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
      - name: Move _next folder to /xiroicon/
        run: |
          mkdir -p /xiroicon
          mv ./_next ./xiroicon/
      - name: Deploy to www.niceicons.com
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/
